#pragma once

#define Animation_BusterShot_Bullet_Init										"Animation_BusterShot_Bullet_Init"
#define Animation_BusterShot_Bullet_Explosive									"Animation_BusterShot_Bullet_Explosive"

#define Animation_HeadGunner_Bullet												"Animation_HeadGunner_Bullet"

#define Animation_HeadGunner_Idle												"Animation_HeadGunner_Idle"
#define Animation_HeadGunner_Shoot_1											"Animation_HeadGunner_Shoot_1"
#define Animation_HeadGunner_Shoot_2											"Animation_HeadGunner_Shoot_2"
#define Animation_HeadGunner_End												"Animation_HeadGunner_End"

#define Animation_MegaManX_Init													"Animation_MegaManX_Init"
#define Animation_MegaManX_InitLand												"Animation_MegaManX_InitLand"
#define Animation_MegaManX_Idle													"Animation_MegaManX_Idle"
#define Animation_MegaManX_Idle_Shoot											"Animation_MegaManX_Idle_Shoot"
#define Animation_MegaManX_Dash													"Animation_MegaManX_Dash"
#define Animation_MegaManX_Dash_Shoot											"Animation_MegaManX_Dash_Shoot"
#define Animation_MegaManX_Run													"Animation_MegaManX_Run"
#define Animation_MegaManX_Run_Shoot											"Animation_MegaManX_Run_Shoot"
#define Animation_MegaManX_Fall													"Animation_MegaManX_Fall"
#define Animation_MegaManX_Fall_Shoot											"Animation_MegaManX_Fall_Shoot"
#define Animation_MegaManX_Landfall												"Animation_MegaManX_Landfall"
#define Animation_MegaManX_Landfall_Shoot										"Animation_MegaManX_Landfall_Shoot"
#define Animation_MegaManX_Jump													"Animation_MegaManX_Jump"
#define Animation_MegaManX_Jump_Shoot											"Animation_MegaManX_Jump_Shoot"
#define Animation_MegaManX_Wall_Clinging										"Animation_MegaManX_Wall_Clinging"
#define Animation_MegaManX_Wall_Clinging_Shoot									"Animation_MegaManX_Wall_Clinging_Shoot"
#define Animation_MegaManX_Idle_Cut												"Animation_MegaManX_Idle_Cut"
#define Animation_MegaManX_Jump_Cut												"Animation_MegaManX_Jump_Cut"
#define Animation_MegaManX_Sky_Walk												"Animation_MegaManX_Sky_Walk"
#define Animation_MegaManX_WasHit												"Animation_MegaManX_WasHit"

#define Animation_MapBehind_1													"Animation_MapBehind_1"
#define Animation_Ready															"Animation_Ready"

#define Animation_Machine_1_Run													"Animation_Machine_1_Run"
#define Animation_Machine_1_Idle												"Animation_Machine_1_Idle"

#define Animation_Notor_Banger_Idle												"Animation_Notor_Banger_Idle"
#define Animation_Notor_Banger_Jump												"Animation_Notor_Banger_Jump"
#define Animation_Notor_Banger_0												"Animation_Notor_Banger_0"
#define Animation_Notor_Banger_30												"Animation_Notor_Banger_30"
#define Animation_Notor_Banger_45												"Animation_Notor_Banger_45"
#define Animation_Notor_Banger_60												"Animation_Notor_Banger_60"
#define Animation_Notor_Banger_90												"Animation_Notor_Banger_90"

#define Animation_Genjibo														"Animation_Genjibo"
#define Animation_Genjibo_Missle_Down											"Animation_Genjibo_Missle_Down"

#define Animation_Shurikein_Init												"Animation_Shurikein_Init"
#define Animation_Shurikein_Spinning											"Animation_Shurikein_Spinning"
#define Animation_Shurikein_WasHit												"Animation_Shurikein_WasHit"
#define Animation_Shurikein_WasHit_3D											"Animation_Shurikein_WasHit_3D"

#define Animation_BlastHornet_Flying											"Animation_BlastHornet_Flying"
#define Animation_BlastHornet_StartAttacking									"Animation_BlastHornet_StartAttacking"
#define Animation_BlastHornet_Shooting											"Animation_BlastHornet_Shooting"
#define Animation_BlastHornet_Died												"Animation_BlastHornet_Died"
#define Animation_BlastHornet_Wing												"Animation_BlastHornet_Wing"
#define Animation_BlastHornet_Child_Flying										"Animation_BlastHornet_Child_Flying"
#define Animation_BlastHornet_Bullet_flying										"Animation_BlastHornet_Bullet_flying"
#define Animation_BlastHornet_Bullet_targeted									"Animation_BlastHornet_Bullet_targeted"

#define Animation_Door1_Open													"Animation_Door1_Open"
#define Animation_Door2_Open													"Animation_Door2_Open"
#define Animation_Door1_Close													"Animation_Door1_Close"
#define Animation_Door2_Close													"Animation_Door2_Close"

#define Animation_Effect_BluePower												"Animation_Effect_BluePower"
#define Animation_Effect_OrangePower											"Animation_Effect_OrangePower"
#define Animation_Effect_Dash													"Animation_Effect_Dash"
#define Animation_Effect_SmokeDash												"Animation_Effect_SmokeDash"
#define Animation_Effect_Smoke													"Animation_Effect_Smoke"
#define Animation_Effect_DoubleJump												"Animation_Effect_DoubleJump"
#define Animation_Effect_Die													"Animation_Effect_Die"
#define Animation_Effect_Explode												"Animation_Effect_Explode"
#define Animation_Effect_Explode_Blue											"Animation_Effect_Explode_Blue"

#define Animation_Carry_Aim_Fly													"Animation_Carry_Aim_Fly"
#define Animation_Carry_Aim_Fly_Explode											"Animation_Carry_Aim_Fly_Explode"
	
#define Animation_MetaCapsule_Open												"Animation_MetaCapsule_Open"
#define Animation_MetaCapsule_Close												"Animation_MetaCapsule_Close"
#define Animation_MetaCapsule_Bullet											"Animation_MetaCapsule_Bullet"

#define Animation_Helit_Fly														"Animation_Helit_Fly"
#define Animation_Helit_Missle													"Animation_Helit_Missle"

#define Bool_IsIdle																"Bool_IsIdle"
#define Bool_IsJump																"Bool_IsJump"
#define Bool_Is0																"Bool_Is0"
#define Bool_Is30																"Bool_Is30"
#define Bool_Is45																"Bool_Is45"
#define Bool_Is60																"Bool_Is60"
#define Bool_Is90																"Bool_Is90"
#define Bool_IsShoot															"Bool_IsShoot"
#define Bool_IsCollision														"Bool_IsCollision"
#define Bool_IsRun																"Bool_IsRun"
#define Bool_IsCut																"Bool_IsCut"
#define Bool_IsIdle																"Bool_IsIdle"
#define Bool_IsFall																"Bool_IsFall"
#define Bool_IsLandFall															"Bool_IsLandFall"
#define Bool_IsDash																"Bool_IsDash"
#define Bool_IsClinging															"Bool_IsClinging"
#define Bool_IsSkyWalk															"Bool_IsSkyWalk"
#define Bool_IsWasHit															"Bool_IsWasHit"
#define Bool_IsOpen																"Bool_IsOpen"
#define Bool_IsAttack															"Bool_IsAttack"
#define Bool_IsDead																"Bool_IsDead"
#define Bool_IsTargeted															"Bool_IsTargeted"

#define Texture_EnemiesAndBosses												"Texture_EnemiesAndBosses"
#define Texture_EnemiesAndBosses												"Texture_EnemiesAndBosses"
#define Texture_X3_Specific														"Texture_X3_Specific"
#define Texture_MegaManX														"Texture_MegaManX"
#define Texture_MegaManX_Dash													"Texture_MegaManX_Dash"
#define Texture_MegaManX_Dash_Shoot												"Texture_MegaManX_Dash_Shoot"
#define Texture_MegaManX_Power													"Texture_MegaManX_Power"
#define Texture_Map_Objects														"Texture_Map_Objects"
#define Texture_Map																"Texture_Map"
#define Texture_WeaponsAndItems													"Texture_WeaponsAndItems"
#define Texture_Door															"Texture_Door"
#define Texture_Health_Bar														"Texture_Health_Bar"
#define Texture_MegaManX_Effect													"Texture_MegaManX_Effect"
#define Texture_MegaManX_Explosions_Effect										"Texture_MegaManX_Explosions_Effect"
#define Texture_Blast_Hornet													"Texture_Blast_Hornet"
#define Texture_Helit															"Texture_Helit"
#define Texture_Ready															"Texture_Ready"

#define Prefab_NotorBanger														"Prefab_NotorBanger"
#define Prefab_NotorBanger_Bullet												"Prefab_NotorBanger_Bullet"
#define Prefab_HeadGunner														"Prefab_HeadGunner"
#define Prefab_HeadGunner_Bullet												"Prefab_HeadGunner_Bullet"
#define Prefab_MapBehind_1														"Prefab_MapBehind_1"
#define Prefab_BusterShot_Bullet												"Prefab_BusterShot_Bullet"
#define Prefab_BusterShot														"Prefab_BusterShot"
#define Prefab_Ladder1															"Prefab_Ladder1"
#define Prefab_Ladder2															"Prefab_Ladder2"
#define Prefab_BrokenWall_Left													"Prefab_BrokenWall_Left"
#define Prefab_BrokenWall_Right													"Prefab_BrokenWall_Right"
#define Prefab_Door1															"Prefab_Door1"
#define Prefab_Door2															"Prefab_Door2"
#define Prefab_Carry_Aim														"Prefab_Carry_Aim"
#define Prefab_Box																"Prefab_Box"
#define Prefab_MetaCapsule														"Prefab_MetaCapsule"
#define Prefab_MetaCapsule_Bullet												"Prefab_MetaCapsule_Bullet"
#define Prefab_BlastHornet_Child												"Prefab_BlastHornet_Child"
#define Prefab_BlastHornet_Child2												"Prefab_BlastHornet_Child2"
#define Prefab_BlastHornet_Bullet												"Prefab_BlastHornet_Bullet"
#define Prefab_Helit															"Prefab_Helit"
#define Prefab_Helit_Missle														"Prefab_Helit_Missle"

#define Prefab_Effect_Dash														"Prefab_Effect_Dash"
#define Prefab_Effect_SmokeDash													"Prefab_Effect_SmokeDash"
#define Prefab_Effect_Smoke														"Prefab_Effect_Smoke"
#define Prefab_Effect_DoubleJump												"Prefab_Effect_DoubleJump"
#define Prefab_Effect_Die														"Prefab_Effect_Die"
#define Prefab_Effect_Explode													"Prefab_Effect_Explode"
#define Prefab_Effect_Explode_Blue												"Prefab_Effect_Explode_Blue"

#define Audio_Sound_Track														"Audio_Sound_Track"
#define Audio_MegaMan_Shoot														"Audio_MegaMan_Shoot"
#define Audio_MegaMan_Power_Shoot												"Audio_MegaMan_Power_Shoot"

#define DESTROY_TIME															3000
#define RELOAD_TIME																2000
#define WASHIT_TIMEOUT															2000

#define EFFECT_POOL_SIZE														20
#define BULLET_POOL_SIZE														20